version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: stefan
      POSTGRES_DATABASE: ss90-blog
      POSTGRESS_USER: stefan
      POSTGRES_PASSWORD: stefan
    ports:
      - "5433:5432"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/ss90-blog"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: postgres
      DB_NAME: ss90-blog
      DB_PASSWORD: stefan
      DB_HOST: db  